import { Geist, Geist_Mono, Brygada_1918 } from 'next/font/google';
import "./globals.css";
import Header from "./layout/header/Header";
import Footer from "./layout/footer/Footer";
import { AuthProvider } from './provider';
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const brygada1918 = Brygada_1918({
  variable: "--font-brygada-1918",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Sunita Gemstones",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={brygada1918.className} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${brygada1918.variable} antialiased`}
        suppressHydrationWarning
      >
        <Header />
        <AuthProvider>
          <ToastContainer
            position="top-right"
            autoClose={5000}
            hideProgressBar={false}
            closeOnClick
            pauseOnHover
            draggable
            pauseOnFocusLoss
            theme="light"
            newestOnTop={false}
          />
          {children}
        </AuthProvider>
        <Footer />
      </body>
    </html>
  );
}
